language: node_js

notifications:
  email: false

env:
  global:

before_install:

install:
  - npm install

after_success:

deploy:
  skip_cleanup: true
  provider: heroku

matrix:
  fast_finish: true