language: node_js

notifications:
  email: false

node_js:
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

env:
  global:

before_install:

install:
  - npm install

after_success:

deploy:
  skip_cleanup: true
  provider: heroku

matrix:
  fast_finish: true
